"""musapy: Python + Rust + MUSA scientific computing library."""

from ._core import (
    # version + startup
    __version__,
    startup_report,
    # classes
    Device,
    Dtype,
    Stream,
    Array,
    # functions
    array,
    add,
    sub,
    mul,
    div,
    pow,
    sin,
    cos,
    exp,
    log,
    abs,
    sign,
    neg,
    clamp,
    eq,
    ne,
    lt,
    gt,
    le,
    ge,
    sum,
    prod,
    max,
    min,
    mean,
    argmax,
    argmin,
    cumsum,
    # linalg ops (v0.3 Phase 2)
    matmul,
    dot,
    solve,
    # linalg decomp ops (v0.3 Phase 3)
    lu,
    qr,
    svd,
    # creation ops (Phase 5)
    zeros,
    ones,
    full,
    eye,
    arange,
    linspace,
    zeros_like,
    ones_like,
    # indexing ops (Phase 6)
    transpose,
    permute,
    flip,
    index_select,
    slice,
    # indexing copy ops (Phase 6.5-7)
    contiguous,
    gather,
    scatter,
    set_default_device,
    set_default_dtype,
    device,
    dtype,
    stream,
    memory_summary,
    device_summary,
    set_debug,
    debug,
    # dtype constants
    bool as bool_,
    int8,
    int16,
    int32,
    int64,
    uint8,
    uint16,
    uint32,
    uint64,
    float16,
    float32,
    float64,
    bfloat16,
    complex64,
    complex128,
    # exceptions
    MusapyError,
    DeviceError,
    DeviceNotConfiguredError,
    DtypeError,
    ShapeError,
    MemoryError,
    OutOfMemoryError,
    StreamError,
    KernelError,
    InteropError,
    LinAlgError,
)

# 命名空间子模块（ADR-003 003-D7）：ms.random（Phase 4）
from . import random

__all__ = [
    # version + startup
    "__version__",
    "startup_report",
    # classes
    "Device",
    "Dtype",
    "Stream",
    "Array",
    # functions
    "array",
    "add",
    "sub",
    "mul",
    "div",
    "pow",
    "sin",
    "cos",
    "exp",
    "log",
    "abs",
    "sign",
    "neg",
    "clamp",
    "eq",
    "ne",
    "lt",
    "gt",
    "le",
    "ge",
    "sum",
    "prod",
    "max",
    "min",
    "mean",
    "argmax",
    "argmin",
    "cumsum",
    # linalg ops (v0.3 Phase 2)
    "matmul",
    "dot",
    "solve",
    # linalg decomp ops (v0.3 Phase 3)
    "lu",
    "qr",
    "svd",
    # creation ops (Phase 5)
    "zeros",
    "ones",
    "full",
    "eye",
    "arange",
    "linspace",
    "zeros_like",
    "ones_like",
    # indexing ops (Phase 6)
    "transpose",
    "permute",
    "flip",
    "index_select",
    "slice",
    # indexing copy ops (Phase 6.5-7)
    "contiguous",
    "gather",
    "scatter",
    "set_default_device",
    "set_default_dtype",
    "device",
    "dtype",
    "stream",
    "memory_summary",
    "device_summary",
    "set_debug",
    "debug",
    # dtype constants
    "bool_",
    "int8",
    "int16",
    "int32",
    "int64",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float16",
    "float32",
    "float64",
    "bfloat16",
    "complex64",
    "complex128",
    # exceptions
    "MusapyError",
    "DeviceError",
    "DeviceNotConfiguredError",
    "DtypeError",
    "ShapeError",
    "MemoryError",
    "OutOfMemoryError",
    "StreamError",
    "KernelError",
    "InteropError",
    "LinAlgError",
]
