"""Type stubs for musapy._core (Rust extension module).

Generated for musapy v0.1.0-alpha.
"""

import builtins
from types import TracebackType
from typing import Any, Sequence, Union

# ============================================================
# Version
# ============================================================

__version__: str

def startup_report() -> str: ...

# ============================================================
# Exceptions (ADR L3-7)
# ============================================================

class MusapyError(Exception): ...
class DeviceError(MusapyError): ...
class DeviceNotConfiguredError(DeviceError): ...
class DtypeError(MusapyError): ...
class ShapeError(MusapyError): ...
class MemoryError(MusapyError): ...  # noqa: A001 — shadows builtin
class OutOfMemoryError(MemoryError): ...
class StreamError(MusapyError): ...
class KernelError(MusapyError): ...
class InteropError(MusapyError): ...
class LinAlgError(MusapyError): ...

# ============================================================
# Device (ADR L1-1, L0-8)
# ============================================================

class Device:
    def __init__(self, spec: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, fmt: str) -> str: ...
    def __eq__(self, other: object) -> builtins.bool: ...
    def __hash__(self) -> int: ...
    @property
    def is_musa(self) -> builtins.bool: ...
    @property
    def musa_id(self) -> int | None: ...
    @property
    def resolution_source(self) -> str | None: ...

# ============================================================
# Dtype (ADR L1-4)
# ============================================================

class Dtype:
    def __init__(self, name: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, fmt: str) -> str: ...
    def __eq__(self, other: object) -> builtins.bool: ...
    def __hash__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def element_size(self) -> int: ...
    @property
    def is_floating(self) -> builtins.bool: ...
    @property
    def is_integer(self) -> builtins.bool: ...
    @property
    def is_complex(self) -> builtins.bool: ...

# ============================================================
# Stream (ADR L1-7, L1-9)
# ============================================================

class Stream:
    def __init__(self, device: str = "cpu", priority: int = 0) -> None: ...
    def synchronize(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @property
    def device(self) -> Device: ...
    @property
    def id(self) -> int: ...
    @property
    def is_poisoned(self) -> builtins.bool: ...
    @property
    def pending_count(self) -> int: ...

# ============================================================
# Array (ADR L1-11, L3-27)
# ============================================================

class Array:
    # Not directly constructible; use ms.array().
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> Dtype: ...
    @property
    def dtype_resolution_source(self) -> str | None: ...
    @property
    def device(self) -> Device: ...
    @property
    def stream(self) -> Stream: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def is_contiguous(self) -> builtins.bool: ...
    @property
    def is_0d(self) -> builtins.bool: ...
    def clear_name(self) -> None: ...
    def tolist(self) -> list[Any]: ...
    def item(self) -> int | float | builtins.bool: ...
    def __add__(self, other: Array) -> Array: ...
    def __sub__(self, other: Array) -> Array: ...
    def __mul__(self, other: Array) -> Array: ...
    def __truediv__(self, other: Array) -> Array: ...
    def __pow__(self, other: Array, modulo: None = None) -> Array: ...
    def __matmul__(self, other: Array) -> Array: ...
    def dot(self, other: Array) -> Array: ...
    def __neg__(self) -> Array: ...
    def __abs__(self) -> Array: ...
    def __eq__(self, other: Array) -> Array: ...  # type: ignore[override]
    def __ne__(self, other: Array) -> Array: ...  # type: ignore[override]
    def __lt__(self, other: Array) -> Array: ...
    def __gt__(self, other: Array) -> Array: ...
    def __le__(self, other: Array) -> Array: ...
    def __ge__(self, other: Array) -> Array: ...
    def astype(self, dtype: Dtype) -> Array: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ============================================================
# Context managers (ADR L2-7, L3-26)
# ============================================================

class _DeviceContext:
    def __enter__(self) -> _DeviceContext: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class _DtypeContext:
    def __enter__(self) -> _DtypeContext: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class _StreamContext:
    def __enter__(self) -> _StreamContext: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class _DebugContext:
    def __enter__(self) -> _DebugContext: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

# ============================================================
# Dtype constants (ADR L1-4)
# ============================================================

bool: Dtype  # noqa: A001 — shadows builtin; use builtins.bool in annotations
int8: Dtype
int16: Dtype
int32: Dtype
int64: Dtype
uint8: Dtype
uint16: Dtype
uint32: Dtype
uint64: Dtype
float16: Dtype
float32: Dtype
float64: Dtype
bfloat16: Dtype
complex64: Dtype
complex128: Dtype

# ============================================================
# Functions
# ============================================================

def array(
    data: Sequence[Any],
    dtype: Dtype | None = None,
    device: str | Device | None = None,
) -> Array: ...

def add(a: Array, b: Array, out: Array | None = None) -> Array: ...
def sub(a: Array, b: Array, out: Array | None = None) -> Array: ...
def mul(a: Array, b: Array, out: Array | None = None) -> Array: ...
def div(a: Array, b: Array, out: Array | None = None) -> Array: ...
def pow(a: Array, b: Array, out: Array | None = None) -> Array: ...
def sin(a: Array, out: Array | None = None) -> Array: ...
def cos(a: Array, out: Array | None = None) -> Array: ...
def exp(a: Array, out: Array | None = None) -> Array: ...
def log(a: Array, out: Array | None = None) -> Array: ...
def abs(a: Array, out: Array | None = None) -> Array: ...  # noqa: A001
def sign(a: Array, out: Array | None = None) -> Array: ...
def neg(a: Array, out: Array | None = None) -> Array: ...
def clamp(a: Array, lo: float, hi: float, out: Array | None = None) -> Array: ...
def eq(a: Array, b: Array, out: Array | None = None) -> Array: ...
def ne(a: Array, b: Array, out: Array | None = None) -> Array: ...
def lt(a: Array, b: Array, out: Array | None = None) -> Array: ...
def gt(a: Array, b: Array, out: Array | None = None) -> Array: ...
def le(a: Array, b: Array, out: Array | None = None) -> Array: ...
def ge(a: Array, b: Array, out: Array | None = None) -> Array: ...

# Reduction (Phase 4)
def sum(a: Array, axis: int | None = None, keepdims: builtins.bool = False, out: Array | None = None) -> Array: ...
def prod(a: Array, axis: int | None = None, keepdims: builtins.bool = False, out: Array | None = None) -> Array: ...
def max(a: Array, axis: int | None = None, keepdims: builtins.bool = False, out: Array | None = None) -> Array: ...
def min(a: Array, axis: int | None = None, keepdims: builtins.bool = False, out: Array | None = None) -> Array: ...
def mean(a: Array, axis: int | None = None, keepdims: builtins.bool = False, out: Array | None = None) -> Array: ...
def argmax(a: Array, axis: int | None = None, out: Array | None = None) -> Array: ...
def argmin(a: Array, axis: int | None = None, out: Array | None = None) -> Array: ...
def cumsum(a: Array, axis: int | None = None, out: Array | None = None) -> Array: ...

# Linalg (v0.3 Phase 2)
def matmul(a: Array, b: Array, out: Array | None = None) -> Array: ...
def dot(a: Array, b: Array, out: Array | None = None) -> Array: ...
def solve(a: Array, b: Array) -> Array: ...

# Linalg decomp (v0.3 Phase 3)
def lu(a: Array) -> tuple[Array, Array]: ...
def qr(a: Array, mode: str = "reduced") -> tuple[Array, Array]: ...
def svd(
    a: Array,
    full_matrices: builtins.bool = True,
    compute_uv: builtins.bool = True,
) -> Array | tuple[Array | None, Array, Array | None]: ...

# Random (v0.3 Phase 4; 由 python/musapy/random.py 包装为 ms.random.* 命名空间)
def rand(
    shape: int | Sequence[int],
    *,
    dtype: Dtype | None = None,
    device: str | Device | None = None,
    seed: int | None = None,
) -> Array: ...
def randn(
    shape: int | Sequence[int],
    *,
    dtype: Dtype | None = None,
    device: str | Device | None = None,
    seed: int | None = None,
) -> Array: ...
def uniform(
    low: float = 0.0,
    high: float = 1.0,
    shape: int | Sequence[int] | None = None,
    *,
    dtype: Dtype | None = None,
    device: str | Device | None = None,
    seed: int | None = None,
) -> Array: ...
def normal(
    loc: float = 0.0,
    scale: float = 1.0,
    shape: int | Sequence[int] | None = None,
    *,
    dtype: Dtype | None = None,
    device: str | Device | None = None,
    seed: int | None = None,
) -> Array: ...
def bernoulli(
    p: float = 0.5,
    shape: int | Sequence[int] | None = None,
    *,
    device: str | Device | None = None,
    seed: int | None = None,
) -> Array: ...

# FFT (v0.3 Phase 5; 由 python/musapy/fft.py 包装为 ms.fft.* 命名空间)
# 注意：axis 目前仅支持 -1（fftn/多轴推迟）；输出恒 complex。
def fft(
    a: Array,
    n: int | None = None,
    axis: int = -1,
    norm: str | None = None,
    out: Array | None = None,
) -> Array: ...
def ifft(
    a: Array,
    n: int | None = None,
    axis: int = -1,
    norm: str | None = None,
    out: Array | None = None,
) -> Array: ...
def rfft(
    a: Array,
    n: int | None = None,
    axis: int = -1,
    norm: str | None = None,
    out: Array | None = None,
) -> Array: ...

# Creation (Phase 5)
def zeros(shape: int | Sequence[int], *, dtype: Dtype | None = None, device: str | Device | None = None) -> Array: ...
def ones(shape: int | Sequence[int], *, dtype: Dtype | None = None, device: str | Device | None = None) -> Array: ...
def full(shape: int | Sequence[int], fill_value: float, *, dtype: Dtype | None = None, device: str | Device | None = None) -> Array: ...
def eye(n: int, m: int | None = None, k: int = 0, *, dtype: Dtype | None = None, device: str | Device | None = None) -> Array: ...
def arange(start: float, stop: float | None = None, step: float = 1.0, *, dtype: Dtype | None = None, device: str | Device | None = None) -> Array: ...
def linspace(start: float, stop: float, num: int = 50, *, dtype: Dtype | None = None, device: str | Device | None = None) -> Array: ...
def zeros_like(a: Array) -> Array: ...
def ones_like(a: Array) -> Array: ...

# Indexing (Phase 6)
def transpose(a: Array, axes: Sequence[int] | None = None) -> Array: ...
def permute(a: Array, dims: Sequence[int]) -> Array: ...
def flip(a: Array, axis: int) -> Array: ...
def index_select(a: Array, axis: int, index: int) -> Array: ...
def slice(a: Array, specs: Sequence[Sequence[int]]) -> Array: ...
def contiguous(a: Array) -> Array: ...
def gather(a: Array, indices: Array, axis: int = 0) -> Array: ...
def scatter(a: Array, indices: Array, values: Array, axis: int = 0) -> Array: ...

def set_default_device(device: str | Device) -> None: ...
def set_default_dtype(dtype: Dtype) -> None: ...

def device(device: str | Device) -> _DeviceContext: ...
def dtype(dtype: Dtype) -> _DtypeContext: ...
def stream(stream: Stream) -> _StreamContext: ...

def memory_summary(device: str | Device | None = None) -> str: ...
def device_summary() -> str: ...

def set_debug(enabled: builtins.bool) -> None: ...
def debug() -> _DebugContext: ...
